import React from 'react';
import Card from 'react-bootstrap/Card';
import '../App.css';

const MyCard = () => {
  return (
    <div>
     <div className='cardhead'> 
      <h1>Sample Books Generated by BookAI</h1>
      <p>Explore some of the captivating books created using our AI technology.</p>
      </div>
      
    <div className='mycard-container'>
      <Card className='mycard'>
        <Card.Img variant="top" className='c-1' src='https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/paradox.png' />
        <Card.Body>
          <Card.Title>Science Fiction</Card.Title>
          <Card.Text className='custom-quote'>
          "As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands..."
          </Card.Text>
          <span style={{ color: '#6F25B4' }} onClick={() => window.location.href = '/'}>Read More</span>
        </Card.Body>
      </Card>
      <Card className='mycard'>
        <Card.Img variant="top" className='c-2' src='https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/mist.png' />
        <Card.Body>
          <Card.Title>Card Title</Card.Title>
          <Card.Text className='custom-quote'>
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </Card.Text>
          <span style={{ color: '#6F25B4' }} onClick={() => window.location.href = '/'}>Read More</span>
        </Card.Body>
      </Card>
      <Card className='mycard'>
        <Card.Img variant="top" className='c-3' src='https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/ecos.png' />
        <Card.Body>
          <Card.Title>Card Title</Card.Title>
          <Card.Text className='custom-quote'>
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </Card.Text>
          <span style={{ color: '#6F25B4' }} onClick={() => window.location.href = '/'}>Read More</span>
        </Card.Body>
      </Card>
    </div>
    </div>
  );
}

export default MyCard;
